name: Deploy AEO SaaS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        npm install
        cd frontend
        npm install

    - name: Build Frontend
      run: |
        cd frontend
        npm run build

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: deploy
        key: ${{ secrets.DEPLOY_KEY }}
        source: "dist/*,server.js,package.json"
        target: "/var/www/aeo-saas/"

    - name: Restart Application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: deploy
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /var/www/aeo-saas
          npm install --production
          pm2 reload all 